version: "2"
services:
  switchconfig-server:
    build: .
    ports:
      - 8088:80
    volumes:
      # You need to copy the config.php.example to config.php
      # and change db parameters to the ones used below
      - ./config.php:/var/www/switchconfig/config.php
