services:
  switchconfig-server:
    build: .
    ports:
      - 8088:80
    volumes:
      # You need to copy the config.php.example to config.php
      # and add your swicthes and options
      - ./config.php:/var/www/switchconfig/config.php
